# Dahil edilen şablon(lar)ı değişken override ederek özelleştirebilirsiniz.
# SAST özelleştirme: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection özelleştirme: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning özelleştirme: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning özelleştirme: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Ortam değişkenleri birden fazla yerde tanımlanabilir.
# Öncelik sırası: https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
